# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topPod', '0002_sport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='image',
        ),
        migrations.AddField(
            model_name='sport',
            name='gliphicon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
