# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topPod', '0003_auto_20170918_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='gliphicon',
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(default='mdeia/default.png', upload_to='sport_images'),
        ),
    ]
