# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topPod', '0004_auto_20170918_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='pod_images'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='sport_images'),
        ),
    ]
