# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topPod', '0005_auto_20170918_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='slug',
        ),
        migrations.AddField(
            model_name='pod',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pod',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
