# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topPod', '0006_auto_20171018_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
